Movie page/update styles
JakubJachacz/Movies-Browser pull request #32
Opened 2023-06-02 13:54 UTC by AngelikaKrygier

2023-06-02 14:34 UTC, RadekW86 commented on src/common/content/MainTile/index.js
> +            {firstInformation === null ? (
are you sure, that no information about production countries return as null not empty array?

2023-06-02 14:41 UTC, RadekW86 commented on src/common/content/MainTile/styled.js
> +    margin: 0 0 8px;
margin-bottom?
+ this property is ignored in devtools
![image](https://github.com/JakubJachacz/Movies-Browser/assets/120674494/50ce293a-c3cd-4dff-b645-254cf31134cc)

2023-06-02 14:43 UTC, RadekW86 commented on src/common/content/MainTile/styled.js
> -
this added a coma between production countries, without it they collapse on one another.
![image](https://github.com/JakubJachacz/Movies-Browser/assets/120674494/66496392-20e3-4ca2-a29a-0acbca7467d6)

2023-06-02 14:50 UTC, RadekW86 commented on src/common/content/MainTile/styled.js
> +  grid-template-columns: 1f 1fr;
what does 1f in:
grid-template-columns: **1f** 1fr; 
mean?

2023-06-02 14:53 UTC, RadekW86 requested changes
please refer to comments in MainTile index and style

2023-06-02 16:01 UTC, AngelikaKrygier commented on src/common/content/MainTile/index.js
> +            {firstInformation === null ? (
I'll check it.

2023-06-02 16:01 UTC, AngelikaKrygier commented on src/common/content/MainTile/styled.js
> +    margin: 0 0 8px;
Because this property uses the tile without the modifier "movies".

![image](https://github.com/JakubJachacz/Movies-Browser/assets/123166327/df32a6f8-3227-4a88-9c30-ae6a9c284414)

2023-06-02 16:01 UTC, AngelikaKrygier commented on src/common/content/MainTile/styled.js
> -
I think this is a safer solution:
                  <ProductionWrapper>
                    {firstInformation.map((country, index) => (
                      <ProductionItem key={country.id}>
                        {`${country.name}${
                          index === firstInformation.length - 1 ? "" : ", "
                        }`}
                      </ProductionItem>
                    ))}
                  </ProductionWrapper>

2023-06-02 16:01 UTC, AngelikaKrygier commented on src/common/content/MainTile/styled.js
> +  grid-template-columns: 1f 1fr;
Obvious typo.

2023-06-02 18:20 UTC, RadekW86 approved these changes

2023-06-03 02:17 UTC, JakubJachacz approved these changes

2023-06-03 08:12 UTC, merged